
export const FETCH_SITS = 'FETCH_SITS';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_RESERVATION_FORM = 'FETCH_RESERVATION_FORM';
export const CATCH_MOVIE = 'CATCH_MOVIE';
export const CATCH_DATE = 'CATCH_DATE';

